language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: "Test"
      script: yarn test
    - stage: "Deploy"
      node_js: "10"
      script: yarn build
      deploy:
        provider: npm
        email: dulowski.marek@gmail.com
        api_key: "$NPM_DEPLOY_API_KEY"
        skip_cleanup: true
        on:
          tags: true
