version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/.tmp

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - default-{{ checksum "package.json" }}
            - default-

      - run: yarn install

      - save_cache:
          key: default-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: yarn run build
      - persist_to_workspace:
          # We publish only ES module artifacts,
          # because the library is only to be used
          # by Typescript environments.
          root: ./

          # Include all paths
          paths:
            - dist

  publish:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/.tmp

    steps:
      - checkout
      - run: echo //registry.npmjs.org/:_authToken=${TOKEN} > ./.npmrc
      - attach_workspace:
          at: ./

      - run: npm publish

  cleanup:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/.tmp

    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: yarn run cleanup

workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - publish:
          context: npmauth
          requires:
              - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
