version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/tmp

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - default-{{ checksum "package.json" }}
            - default-

      - run: yarn install

      - save_cache:
          key: default-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: yarn run build
      - persist_to_workspace:
          # We publish only ES module artifacts,
          # because the library is only to be used
          # by Typescript environments.
          root: ./

          # Include all paths
          paths:
            - dist

  test:
    docker:
      - image: circleci/node:latest

    working_directory: ~/tmp

    steps:
      - checkout

      - run: yarn install
      - run: yarn test

  publish:
    docker:
      - image: circleci/node:latest

    working_directory: ~/tmp

    steps:
      - checkout
      - run: echo //registry.npmjs.org/:_authToken=${TOKEN} > ./.npmrc
      - attach_workspace:
          at: ./

      - run: npm publish

workflows:
  version: 2
  "Build and publish":
    jobs:
      - build:
          filters:
            branches:
              only: master

      - publish:
          context: npmauth
          requires:
            - build
          filters:
            branches:
              only: master